github: ichinya
custom: [
  'https://donate.stream/ichi',
  'https://yoomoney.ru/fundraise/gpJtjQCridM.230427',
  'https://www.tinkoff.ru/cf/Axly4z6DnEF',
  'https://new.donatepay.ru/@ichi',
  'https://www.donationalerts.com/r/ichi_nya',
]
